const CONSTANTS = {
  PIXEL_SIZE: 12,
  STARTING_PIXEL_GRID_HEIGHT: 64,
  STARTING_PIXEL_GRID_WIDTH: 64,
  DEFAULT_SELECTED_PRIMARY_COLOR: "000", // hex (without #)
  DEFAULT_SELECTED_SECONDARY_COLOR: "FFF", // hex (without #)
  CANVAS_UNDERLAY_COLORS: ["#cccccc", "#ffffff"],

  BACKGROUND_COLOR: "#333",
};

export default CONSTANTS;
